CREATE DATABASE QUANLYBAOTRITHIETBI;
GO
USE QUANLYBAOTRITHIETBI;
GO

-- Bảng Thiết bị
CREATE TABLE THIET_BI (
    MaTB VARCHAR(10) PRIMARY KEY,
    TenTB NVARCHAR(100) NOT NULL,
    LoaiTB NVARCHAR(50),
    ViTri NVARCHAR(100),
    TrangThai NVARCHAR(50) DEFAULT N'Hoạt động'
);

-- Bảng Nhân viên
CREATE TABLE NHAN_VIEN (
    MaNV VARCHAR(10) PRIMARY KEY,
    HoTen NVARCHAR(50) NOT NULL,
    ChuyenMon NVARCHAR(100),
    SoDienThoai VARCHAR(15)
);

-- Bảng Phiếu bảo trì
CREATE TABLE PHIEU_BAO_TRI (
    MaPhieu VARCHAR(10) PRIMARY KEY,
    MaTB VARCHAR(10) FOREIGN KEY REFERENCES THIET_BI(MaTB),
    MaNV VARCHAR(10) FOREIGN KEY REFERENCES NHAN_VIEN(MaNV),
    NgayThucHien DATETIME DEFAULT GETDATE(),
    NoiDung NVARCHAR(MAX),
    ChiPhi DECIMAL(18, 2) CHECK (ChiPhi >= 0),
    KetQua NVARCHAR(100)
);